const actions = {
  DATA_FETCHING: "DATA_FETCHING",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_FETCHING_FAILURE: "DATA_FETCHING_FAILURE",
<<<<<<< HEAD
=======
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",
>>>>>>> 1aca51e336bc0eb22414ee294b6d79b89cdd7003
};

export default actions;
