const actions = {
  DATA_FETCHING: "DATA_FETCHING",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_FETCHING_FAILURE: "DATA_FETCHING_FAILURE",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

  UPDATE_LOGIN_STATUS: "UPDATE_LOGIN_STATUS",

  GET_USER_CART: "GET_USER_CART",
  GET_USER_CART_SUCCESS: "GET_USER_CART_SUCCESS",
  GET_USER_CART_FAILURE: "GET_USER_CART_FAILURE",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",

  GET_CATEGORY_NAME: "GET_CATEGORY_NAME",
  GET_CATEGORY_NAME_SUCCESS: "GET_CATEGORY_NAME_SUCCESS",
  GET_CATEGORY_NAME_FAILURE: "GET_CATEGORY_NAME_FAILURE",
};

export default actions;
