const actions = {
  DATA_FETCHING: "DATA_FETCHING",
  DATA_SUCCESS: "DATA_SUCCESS",
  DATA_FETCHING_FAILURE: "DATA_FETCHING_FAILURE",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",
};

export default actions;
